# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XEngineApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'LSRFramework'
  pod 'JSONModel'
  pod 'SSZipArchive'
  pod 'AFNetworking'
  # Pods for UIModule
  pod 'XEngineSDK', :path =>'../'
  # Pods for XEngineApp

end
