# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XEngineApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

 # Pods for XEngineApp
  pod 'LSRFramework'
  pod 'JSONModel'
  pod 'SSZipArchive'
  pod 'AFNetworking'

  # Pods for UIModule
  pod 'XEngineSDK', :path =>'../'

  # Pods for XEngineNavigationModule
  pod 'XEngineNavigationModule', :path =>'../'

  # Pods for XEngineNetworkModule
  pod 'XEngineNetworkModule', :path =>'../'

  # Pods for XEngineTabBarControllerModule
  pod 'XEngineTabBarControllerModule', :path =>'../'



 # Pods for TimesHomeSDKDemo
#	pod 'IMSLaunchKit', :path => 'TimesHomeSDK/IMSLaunchKit.podspec'
#	pod 'IMSInitCode', :path => 'TimesHomeSDK/IMSInitCode.podspec'
#    	pod 'IMSGlueCode', :path => 'TimesHomeSDK/IMSGlueCode.podspec'
#    	pod 'XLHContainerFramework', :path => 'TimesHomeSDK/XLHContainerFramework.podspec'
#	pod 'XGHomeSDK', :path => 'TimesHomeSDK/XGHomeSDK.podspec'
end
